- reindex.js
This criterion is use to "boost" records matching exactly the query words but it makes libraries having "backbone" in their "keywords" attribute being ranked higher than the "backbone.js" library if query is "backbone". Not a big deal, I've just removed it here.
> Remove the "exact" criterion from Algolia's ranking formula

- reindex.js
Ahah, GitHub has automatically revoked the OAuth token we're using because it was in plain text in the code source :) I moved it to an environment variable as well and send you guys the new one.
> Move that non-critical oauth key to an environment variable

- public/js/main.js
This fixes https://github.com/cdnjs/cdnjs/issues/5462 escaping the description before displaying it. We keep the `<em></em>` tags to highlight the matching words.
> Avoid any XSS issue while displaying the package description in the search results

- apiServer.js
This commit replaces the legacy `_.filter`-based search API by Algolia's search.
- fuzzy & multi-attributes search capabilities, (Fix #74)
- handling of the optional `fields` attribute (Fix cdnjs/cdnjs#5688)
> Fuzzy Search

- public/js/main.js
- templates/layout.html
Hello everyone.
This PR is related to issue #94.
The idea is to remove `ZeroClipboard` from the project, thus removing flash completely.
Tried to make the fewer changes possible to make the switch happen. Tough I think the code deserves some refactoring soon.
Besides that I added some tooltip feedback following the `bootstrap` pattern.
That's particularly useful if one is using Safari and need to use `Ctrl-C` or `Command-C` to copy.
On iOS the copy button won't show, that's because it's not elegant to show a button and then discover that it actually won't work. Check [clipboard.js browser support](https://github.com/zenorocha/clipboard.js#browser-support).
The validation for iOS is currently `user-agent` based. I'm open to tips on how to improve that if needed.
Please review the PR and …
> Remove ZeroClipboard in favor of clipboard.js

- public/js/main.js
Hello guys.
PR related to what was discussed in #97.
Made the changes following what @terinjokes pointed out.
Now it is logging the copy action even on the `clipboard error` event that occurs when people need to press `Ctrl-C` or `Command-C` to copy (when using Safari).
Please review.
Thank you.
> Adjust some code regarding the copy button

- reindex.js
@redox I think we didn't use watchers/open_issues_count and think we can remove them in the reindex process, what do you think? Thanks!
> drop watchers/open_issues_count in algolia index process

- webServer.js
Though we are using http/1.1 in express/nodejs, we are using CDN that
supports http/2.0, this header will be sent to CDN server, so that CDN
server will push the files from cache to client.
> server push header added for http/2.0

- public/css/main.css
with all `.btn` elements' padding set to 0px, a bit of padding on specific elements will be needed. This fix covers the `copy` button's missing padding
> fix copy button padding

- templates/library.html
The reddit logo at the bottom of the website causes a mixed content warning.
> Fix HTTP request to i.imgur.com.

- templates/library.html
- webServer.js
PR for #60 
It will show `watch`, `star`, `fork` information on each lib's page.
For the library without git repository(no popularity info), it will show like this:
> add popularity info on each lib's page

- public/js/main.js
- templates/library.html
@PeterDaveHello 
PS: Messed up. Had to create a new PR.
#159
> Show copy button when hovered in package-list/library page

- public/js/main.js
Fixes #164 
Library list was being cleared up when search value was made empty in the "/libraries" page.
However, that is the required behaviour in the "/" page. 
Now "/libraries" page shows up the original list when the search value is empty.
> Fixes 164, Search bar now shows full list when no input

- webServer.js
As discovered while working on #182, page titles weren't displayed for few pages.
This PR fixes the issue of page titles not being displayed for pages — About, API and Library Tutorials.
> Fix page titles not displayed

- templates/notfound.html
- webServer.js
close #78 
@PeterDaveHello As posted [here](https://github.com/cdnjs/new-website/issues/78#issuecomment-304511021), the content inside the template doesn't get displayed on encountering a 404 not found error.
> Implement library not found page

- public/css/theme.css
- templates/layout.html
Hi all,
I made some changes to the menu bar. Below are a couple of things I found a tad distracting:
1. The dropdown buttons (namely, "support," "gource" and "git status") have a slightly wider `margin-top` than the other links.
Here's my current version:
2. The dropdown buttons use Bootstrap's default `btn` class, which has a weird shadow on top that looks a bit out of place.
I changed them to the `btn-link` class, so as to accord with other link buttons.
3. `background-color` of dropdown items does not extend to full width of its parent `div`; I fixed this (see above).
4. Original dropdown menus align with the left border of their toggle elements. I changed them to align with the right border, because the menu items themselves are floating right (see above); I am willing to talk about …
> [Website] Fix menu bar responsive issues

- templates/layout.html
- templates/tutorial.html
This change makes sure highlight.js will only be requested when visiting the tutorial page (closed issue #72).
Also updated highlight.js and styles/monokai-sublime.min.css to their [latest version](https://cdnjs.com/libraries/highlight.js) (v9.12.0).
> [Website] clean up highlight.js (fixed #72)

- templates/layout.html
Changes:
* Community site is currently broken and I've had no reply in some time regarding this - Looks bad to have our community site being linked and also broken
* Rename the Discord link to Community Discord so the community has an obvious place to go still
* Add twitter + discord links to footer (twitter isn't linked anywhere else on site)
Notes:
* Discord icon in footer can be replaced with actual discord icon once https://github.com/cdnjs/new-website/issues/260 / https://github.com/cdnjs/cdnjs/pull/12517 are resolved
* Community forums link can be re-added once the issues with it are resolved if we decide that is worth doing
> [Website] Update community links

- package.json
- webServer.js
Here is the [linked issue](https://github.com/cdnjs/new-website/issues/255)
> [Website] Fix throng dependency vulnerability

- public/js/main.js
- reindex.js
I do have experience in JS but this was the first time I worked with a Node.js project. I would perfectly understand if I made any mistakes.
So I have actually "reported" about this almost a year ago on [Twitter](https://twitter.com/GlennCarremans/status/944140219049234433) and @PeterDaveHello  challenged me to make a PR for it. I have never forgotten about it and now because of Hacktoberfest I decided to make some time for it and try it out.
I also saw some open issues about the same issue:
Fixes #152 SRI support on search result
Fixes cdnjs/cdnjs#12746 Add Copy Script Tag with SRI option
> [Website] Added "Copy Script Tag with SRI" option to library search results

- templates/layout.html
This pull request intends to make the following changes to the website:
- Add Patreon to the Support Us! dropdown as a monthly donation option
- Add Open Collective to the Support Us! dropdown as another monthly donation option
- Add Patreon & Open Collective to the donation message in the footer of the site
- Fix wording of the donation footer, making it flow more easily
> [Website] Update Support Us! links

- public/js/main.js
- templates/layout.html
- templates/library.html
- templates/tutorial.html
This PR fixes #260
**Migrating the website from FontAwesome 4.7.0 to the newer 5.8.2**
- Replace comments icon with correct Discourse icon in footer
- Replace all other icons like for like
> [Website] Migrate from FontAwesome 4.7.0 -> 5.8.2

- public/css/main.css
- templates/layout.html
- Implement a status indicator in the footer of all pages on site, making use of the Statuspage.io JS library (SRI doesn't appear to be supported?).
- Added links to the [status page](https://status.cdnjs.com/) and [status twitter](https://twitter.com/cdnjsStatus) account in the navbar under the Network label (now a dropdown called "Network & Status").
- Move uptime to be under the network/status dropdown.
- Include status indicator next to status page link in navbar dropdown.
> [Website] Add status page to nav w/ indicator dot & add statuspage pop-up

- .eslintignore
- .eslintrc.json
- .travis.yml
- package.json
- reindex.js
- webServer.js
fix current eslint issues:
-  around space-before-function
- paren and no-unused-vars
Fixes #174
> Add eslint

- public/css/main.css
Sorry about this small PR 😅but this really bothered me more than it should.
I did try to look for other small tweaks I could add but didn't find any.
Before:
After:
> [Website] Fix copy button padding

- public/css/main.css
- public/js/main.js
- Surrounded library name and description in a <div> tag when setting up code dynamically
- Made the <div> tag clickable using jQuery
> [Website] Fix #277: Integrated library name and description in one clickable div

- public/css/main.css
- public/css/theme.css
- public/js/main.js
- templates/layout.html
Resolves #258 be correcting the rotation direction and updating the general styling to make it work better on tablets and mobile.
Resolves #18 by making the homepage margin-top responsive on all devices based on viewport height, giving the navigation a margin-top (and re-ordering to prioritise browsing libraries), making the search box larger for easier access on mobile and making the footer margin larger as well as the padding and making the text easier to read.
> [Website] Fix GitHub banner & homepage responsiveness

- public/css/theme.css
- templates/library.html
- webServer.js
As requested by a user, to make it more clear which file is suggested to be used normally.
Highlight the provided filename from the package.json in the full library file view.
Fixes #319
> [Website] Highlight the default file in the library view

- package.json
- public/js/main.js
- templates/library.html
- webServer.js
Refer to #54, the library asset only display *.min.js, *.min.css, and
`filename` field in package.json.
Fixes #54, cc @PeterDaveHello.
> [Website] Display library assets only important files

- apiServer.js
- templates/api.html
Currently /libraries on the API uses in-memory data if no search query is given, which is killing the API app. This changes the behaviour of /libraries to always use Algolia.
> [API] Always use Algolia for /libraries

- webServer/utils/fileType.js
Currently cdnjs saves typescript files but they aren't listed in the cdnjs website. This PR will add them in the js list.
If needed it can be added as a separate list but I noticed that `scss` files are also listed in the css list.
> Show `.ts` files in js list

- webServer/utils/libraries.js
In relation to https://github.com/cdnjs/cdnjs/issues/13986, the newly generated data contains some blank entires that are causing the site to continue to fall over, even after the data corruption issue was resolved.
> Ignore invalid libraries when loading data in

- webServer/utils/libraries.js
As noted in some reports overnight, the site briefly had some bad SRI data that was then cached on certain pages. This PR does NOT fix this.
However, this did raise an issue with the default value used for SRI if it fails to load data. Currently, the logic just reads in the raw JSON file for SRI data and spits it back out. If not SRI data is found, it will attempt to spit out an empty object without converting it to JSON first, resulting in the `[object Object]` reported by some folks.
This changes the logic to parse the read in SRI JSON data first, within the existing try/catch. This is actually better as we'll make sure that the JSON is valid before using it. If reading in the JSON fails, the same fallback empty object will be used. However, as we're now parsing the JSON data, we then …
> Parse & re-stringify JSON SRI data

- apiServer.js
- webServer/app.js
HPKP isn't supported by any mainstream browsers these days[1][2], and
the pins seems to be out-of-date.
[1] https://www.chromestatus.com/feature/5903385005916160
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1412438
> Remove HPKP headers
