cdnjs/new-website

public/js/main.js

Fix for https://github.com/cdnjs/cdnjs/issues/4574

Fix copy button not working w/o flash.

---

README.md

Useful for developers looking to help. ;)

Add missing setup and running instructions.

---

apiServer.js

/cc @PeterDaveHello Does this break any of your scripts or am I fine to merge?

Remove console logs for cleaner production log output

---

templates/about.html
templates/layout.html

Added appropriate classes for responsive video. Required updated of
Bootswatch to 3.3.4

Fixed aspect ration of video on about page

---

reindex.js

Search in the repository URL, owner and maintainer names as well.

---

apiServer.js
package.json

This PR replaces the legacy `_.filter`-based search API by Algolia's search (includes fuzzy & multi-attributes search capabilities). Ref #74

Algolia-based fuzzy search

---

public/js/main.js

Display the highlighted form of the GitHub user+repo as well. Fix #88

Search highlighting

---

public/js/main.js

* It now shows a friendly message if no matches are found.

Update library search result table. Closes #87

---

public/css/theme.css
templates/library.html
webServer.js

Fix copy script/link tag button in lib detail view

---

public/js/main.js

* It now fills issue title and library name with search query. Closes #101

Update request lib link.

---

apiServer.js
templates/layout.html
templates/tutorial.html

Firefox now has bug that will always give this error in the console:
```
None of the "sha256" hashes in the integrity attribute match the content of the subresource.
```
So will wait for the problem been solved.

start to use SRI on cdnjs.com

---

public/css/theme.css

HIRED banner might covered some information from body content.

Fix body style

---

public/js/main.js

On copy/click doesn't move to top of the page

Replace link with javascript

---

apiServer.js
templates/api.html
templates/layout.html
webServer.js

This PR adds an API page to the website, and also fixes #76 .

API page on website.

---

public/css/main.css

I know there is a copy button, but if you are a twat like me, this is seriously saves time, and helps to prevent accidentally copy of "Copy" title of the button.

Added force select when pressing on link

---

templates/library.html

Update library.html template

---

public/js/main.js

Fixes #41 
[Screenshot](http://g.recordit.co/ezZbPdhSVw.gif)

Copy button to disappear on mouseout, fix #41

---

apiServer.js
templates/layout.html

[Website] Move to Algolia's lite build

---

public/js/main.js

close #133.
demo page: http://hare1039.ddns.net:5500/
It is some how slow on Firefox, but fine on chrome.

Add lazy scroll to load more library query result

---

public/js/main.js

Fix errors that I didn't notice in previous PR #161 .
I delete the trailing whitespaces and fix init queries from page 0.
demo at: http://hare1039.nctu.me:5500. Please tell me anything I need to improve. Thanks.

Implement lazy load on library searching

---

public/css/main.css
public/css/theme.css
public/js/main.js
templates/home.html
templates/libraries.html

Display total search results

---

public/js/main.js
templates/layout.html

[Website] Improve reuqest library link

---

templates/home.html

As #202 said
Maybe this function does not take effect immediately, but I'm not sure.
Because I refer to this link https://bloggerspassion.com/google-site-links-how-to-get-google-sitelinks-for-your-website/.
Thanks.

[Website] Add Google's Sitelinks Search Box

---

templates/library.html

Spacing between version-selector and cdn-provider-selector for improved UX

[Website] Improved Library version & CDN provider selector UI

---

templates/layout.html

Add the subreddit link, convert community to a dropdown.
Can add the Discord, if created, at a later date.

Community dropdown, add subreddit

---

templates/layout.html

remove the broken gource links as the navbar is getting crowded and these are broken anyway

[Website] restructure navbar

---

public/js/main.js

[Website] Fix a typo

---

apiServer.js

Reported via Twitter & email, it is possible to perform a full XSS attack of the API site through the fields as we were blindly outputting whatever was provided in HTML.
This adds some basic logic to cleanse all fields so that they don't contain HTML.
An alternative would be to filter the user-provided fields to only be from a known set, but this might be considered breaking fuctionality if people are using the API an expecting the null resposnes to custom fields.

[API] Clean all fields to prevent XSS

---

Procfile

This reverts commit 84d77d0aabebcedea7f30caa6f1ad576db68d938.

Revert "update Procfile"

---

package.json
public/js/main.js

This resolves #297 by updating the test script to ensure ESLint checks public/js/main.js
This also refactors the whole file to give us a cleaner base to work from going forward.
This is a follow-on PR from #298 with the changes split by section in the file. If anyone has an issue and wishes for things to be split further, you are welcome to do this yourself, I do not see a way to split this further nor do I wish to invest the time into doing so.

[Website] Lint & refactor public/js/*.js

---

public/css/theme.css
templates/about.html
templates/api.html
templates/breadcrumbs.html
templates/home.html
templates/layout.html
templates/libraries.html
templates/library.html
templates/tutorial.html
templates/tutorials.html
webServer.js

Resolves #143 by implementing breadcrumbs on all public pages, following the [Schema spec](http://schema.org/BreadcrumbList) for breadcrumb element structure and attributes.
Closes #178 which implements breadcrumbs but does not fully follow the spec.

[Website] Implement breadcrumb on all pages following Schema spec

---

templates/api.html

Rewrote unclear documentation for the `assets` field.
The API docs might have been unclear for some people, I did a couple small changes that hopefully will avoid confusion.
Cause of these changes: https://cdnjs.discourse.group/t/asset-in-api-is-not-loading/291
I also noticed different API docs here (https://api.cdnjs.com/) but couldn't find where I could update this.

[Website] Update API docs

---

.gitmodules
apiServer.js

Adding tutorials to the API so that they can be used on the new, static website.
This also removes all the now archived git stats submodule repos as they're not used.

[API] Add tutorials to the API

---

runServer.sh

Revert "Init and update submodule in run script"
